<?php

$lang['num_word_1']        = 'Egy';
$lang['num_word_2']        = 'Kettő';
$lang['num_word_3']        = 'Három';
$lang['num_word_4']        = 'Négy';
$lang['num_word_5']        = 'Öt';
$lang['num_word_6']        = 'Hat';
$lang['num_word_7']        = 'Hét';
$lang['num_word_8']        = 'Nyolc';
$lang['num_word_9']        = 'Kilenc';
$lang['num_word_10']       = 'Tíz';
$lang['num_word_11']       = 'Tizenegy';
$lang['num_word_12']       = 'Tizenkettő';
$lang['num_word_13']       = 'Tizenhárom';
$lang['num_word_14']       = 'Tizennégy';
$lang['num_word_15']       = 'Tizenöt';
$lang['num_word_16']       = 'Tizenhat';
$lang['num_word_17']       = 'Tizenhét';
$lang['num_word_18']       = 'Tizennyolc';
$lang['num_word_19']       = 'Tizenkilenc';
$lang['num_word_20']       = 'Húsz';
$lang['num_word_21']       = 'Huszonegy';
$lang['num_word_22']       = 'Huszonkettő';
$lang['num_word_23']       = 'Huszonhárom';
$lang['num_word_24']       = 'Huszonnégy';
$lang['num_word_25']       = 'Huszonöt';
$lang['num_word_26']       = 'Huszonhat';
$lang['num_word_27']       = 'Huszonhét';
$lang['num_word_28']       = 'Huszonnyolc';
$lang['num_word_29']       = 'Huszonkilenc';
$lang['num_word_30']       = 'Harminc';
$lang['num_word_31']       = 'Harmincegy';
$lang['num_word_32']       = 'Harminckettő';
$lang['num_word_33']       = 'Harminchárom';
$lang['num_word_34']       = 'Harmincnégy';
$lang['num_word_35']       = 'Harmincöt';
$lang['num_word_36']       = 'Harminchat';
$lang['num_word_37']       = 'Harminchét';
$lang['num_word_38']       = 'Harmincnyolc';
$lang['num_word_39']       = 'Harminckilenc';
$lang['num_word_40']       = 'Negyven';
$lang['num_word_41']       = 'Negyvenegy';
$lang['num_word_42']       = 'Negyvenkettő';
$lang['num_word_43']       = 'Negyvenhárom';
$lang['num_word_44']       = 'Negyvennégy';
$lang['num_word_45']       = 'Negyvenöt';
$lang['num_word_46']       = 'Negyvenhat';
$lang['num_word_47']       = 'Negyvenhét';
$lang['num_word_48']       = 'Negyvennyolc';
$lang['num_word_49']       = 'Negyvenkilenc';
$lang['num_word_50']       = 'Ötven';
$lang['num_word_51']       = 'Ötvenegy';
$lang['num_word_52']       = 'Ötvenkettő';
$lang['num_word_53']       = 'Ötvenhárom';
$lang['num_word_54']       = 'Ötvennégy';
$lang['num_word_55']       = 'Ötvenöt';
$lang['num_word_56']       = 'Ötvenhat';
$lang['num_word_57']       = 'Ötvenhét';
$lang['num_word_58']       = 'Ötvennyolc';
$lang['num_word_59']       = 'Ötvenkilenc';
$lang['num_word_60']       = 'Hatvan';
$lang['num_word_61']       = 'Hatvanegy';
$lang['num_word_62']       = 'Hatvankettő';
$lang['num_word_63']       = 'Hatvanhárom';
$lang['num_word_64']       = 'Hatvannégy';
$lang['num_word_65']       = 'Hatvanöt';
$lang['num_word_66']       = 'Hatvanhat';
$lang['num_word_67']       = 'Hatvanhét';
$lang['num_word_68']       = 'Hatvannyolc';
$lang['num_word_69']       = 'Hatvankilenc';
$lang['num_word_70']       = 'Hetven';
$lang['num_word_71']       = 'Hetvenegy';
$lang['num_word_72']       = 'Hetvenkettő';
$lang['num_word_73']       = 'Hetvenhárom';
$lang['num_word_74']       = 'Hetvennégy';
$lang['num_word_75']       = 'Hetvenöt';
$lang['num_word_76']       = 'Hetvenhat';
$lang['num_word_77']       = 'Hetvenhét';
$lang['num_word_78']       = 'Hetvennyolc';
$lang['num_word_79']       = 'Hetvenkilenc';
$lang['num_word_80']       = 'Nyolcvan';
$lang['num_word_81']       = 'Nyolcvanegy';
$lang['num_word_82']       = 'Nyolcvankettő';
$lang['num_word_83']       = 'Nyolcvanhárom';
$lang['num_word_84']       = 'Nyolcvannégy';
$lang['num_word_85']       = 'Nyolcvanöt';
$lang['num_word_86']       = 'Nyolcvanhat';
$lang['num_word_87']       = 'Nyolcvanhét';
$lang['num_word_88']       = 'Nyolcvan nyolc';
$lang['num_word_89']       = 'Nyolcvankilenc';
$lang['num_word_90']       = 'Kilencven';
$lang['num_word_91']       = 'Kilencvenegy';
$lang['num_word_92']       = 'Kilencvenkettő';
$lang['num_word_93']       = 'Kilencvenhárom';
$lang['num_word_94']       = 'Kilencvennégy';
$lang['num_word_95']       = 'Kilencvenöt';
$lang['num_word_96']       = 'Kilencvenhat';
$lang['num_word_97']       = 'Kilencvenhét';
$lang['num_word_98']       = 'Kilencvennyolc';
$lang['num_word_99']       = 'Kilencvenkilenc';
$lang['num_word_100']      = 'Száz';
$lang['num_word_200']      = 'Kétszáz';
$lang['num_word_300']      = 'Háromszáz';
$lang['num_word_400']      = 'Négyszáz';
$lang['num_word_500']      = 'Ötszáz';
$lang['num_word_600']      = 'Hatszáz';
$lang['num_word_700']      = 'Hétszáz';
$lang['num_word_800']      = 'Nyolcszáz';
$lang['num_word_900']      = 'Kilencszáz';
$lang['num_word_thousand'] = 'Ezer';
$lang['num_word_million']  = 'Millió';
$lang['num_word_billion']  = 'Milliárd';
$lang['num_word_trillion'] = 'Trillió';
$lang['num_word_zillion']  = 'Zillió';
$lang['num_word_cents']    = 'cent';
$lang['number_word_and']   = '-';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Száz';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Szöveggel';

$currencies = [
    'USD' => 'Dollár',
    'EUR' => 'Euró',
    'HUF' => 'Forint',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
